name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.9
            env:
              TOXENV: flake8
          - python-version: 3.9
            env:
              TOXENV: py
          - python-version: "3.10"
            env:
              TOXENV: py
          - python-version: "3.10"
            env:
              TOXENV: latest
          - python-version: "3.11"
            env:
              TOXENV: py
          - python-version: "3.11"
            env:
              TOXENV: latest
          - python-version: "3.12"
            env:
              TOXENV: py
          - python-version: "3.12"
            env:
              TOXENV: latest
          - python-version: "3.13"
            env:
              TOXENV: py
          - python-version: "3.13"
            env:
              TOXENV: latest
          - python-version: "3.13"
            env:
              TOXENV: twinecheck
          - python-version: "3.12"  # Keep in sync with tox.ini
            env:
              TOXENV: docs
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install language-pack-fr
        run: sudo apt-get update && sudo apt-get install -y language-pack-fr build-essential
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tests
        run: tox -e ${{ matrix.env.TOXENV }}
      - name: Upload coverage.xml to codecov
        if: ${{ matrix.env.python-version == '3.9' && matrix.env.TOXENV == 'latest' }}
        uses: codecov/codecov-action@v3

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
